Repository FreeCodeCampChina/challenges, pull requests merged in 2018-07, with the labels that each got.

#14 Add .gitignore
  .gitignore
Labels: ready for review

#11 Translation of intermediate-algorithm-scripting, 50%
  02-javascript-algorithms-and-data-structures/intermediate-algorithm-scripting.json
Labels: comments addressed, ready for review

#15 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: need update, ready for review

#28 Update .gitignore
  .gitignore
Labels: ready for review

#33 翻译格式与建议
  CONTRIBUTING.md
  style-guide.md
Labels: need update

#1 Translate managing-packages-with-npm
  05-apis-and-microservices/managing-packages-with-npm.json
  05-apis-and-microservices/managing-packages-with-npm.md
Labels: :shipit: ship it

#2 Translate responsive-web-design-projects
  01-responsive-web-design/responsive-web-design-projects.json
Labels: :shipit: ship it

#4 Translate information-security-with-helmet
  06-information-security-and-quality-assurance/information-security-with-helmetjs.json
Labels: :shipit: ship it

#12 Translate object-oriented-programming
  02-javascript-algorithms-and-data-structures/object-oriented-programming.json
Labels: :shipit: ship it

#17 Translate basic-css
  01-responsive-web-design/basic-css.json
Labels: :shipit: ship it

#30 Css grid
  01-responsive-web-design/css-grid.json
  01-responsive-web-design/css-grid.md
Labels: :shipit: ship it

#37 更新：翻译格式与建议
  CONTRIBUTING.md
  style-guide.md
Labels: ready for review

#41 (DOC) Workflow details and instruction of fixing wrong files changed
  CONTRIBUTING.md
Labels: ready for review
