Repository FreeCodeCampChina/challenges, pull requests merged in 2018-08, with the labels that each got.

#57 (DOC) CONTRIBUTING.md update
  CONTRIBUTING.md
Labels: ready for review

#56 Revert changes of responsive-web-design-projects introduced in #53
  01-responsive-web-design/responsive-web-design-projects.json
  01-responsive-web-design/responsive-web-design-projects.md
Labels: ready for review

#39 Style update of PR #1 and PR # 2
  01-responsive-web-design/responsive-web-design-projects.json
  05-apis-and-microservices/managing-packages-with-npm.json
Labels: :shipit: ship it

#21 Finish translation of regular expression
  02-javascript-algorithms-and-data-structures/regular-expressions.json
  02-javascript-algorithms-and-data-structures/regular-expressions.md
Labels: need update, ready for review

#60 (new) Finish translation of debugging
  02-javascript-algorithms-and-data-structures/debugging.json
  02-javascript-algorithms-and-data-structures/debugging.md
Labels: :shipit: ship it

#45 Advanced Node and Express Translation
  06-information-security-and-quality-assurance/advanced-node-and-express.json
  06-information-security-and-quality-assurance/advanced-node-and-express.md
Labels: :shipit: ship it

#66 Regular expression follow up
  02-javascript-algorithms-and-data-structures/regular-expressions.json
  02-javascript-algorithms-and-data-structures/regular-expressions.md
Labels: :shipit: ship it, ready for review

#26 Translate basic-node-and-express
  05-apis-and-microservices/basic-node-and-express.json
Labels: :shipit: ship it

#74 Finish translation of web design projects
  01-responsive-web-design/responsive-web-design-projects.json
  01-responsive-web-design/responsive-web-design-projects.md
Labels: :shipit: ship it
